let host = "http://" + window.location.host;

data = {
  August: {
    1: {
      img: host + "/images/01_agosto_2020.jpg",
      title: "17ª Semana do Tempo Comum",
      details:
        "Santo Afonso Maria de Ligório (bispo, doutor e fundador) (Branca - ofício da memória)",
      date: "1 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-1a.html",
    },
    2: {
      img: host + "/images/02_agosto_2020.jpg",
      title: "18º Domingo Do Tempo Comum",
      details: "(Verde - ofício dominical comum)",
      date: "2 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-2a.html",
    },
    3: {
      img: host + "/images/03_agosto_2020.jpg",
      title: "Segunda-feira da 18ª Semana Comum",
      details: "(Verde – ofício do dia)",
      date: "3 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-3a.html",
    },
    4: {
      img: host + "/images/04_agosto_2020.jpg",
      title: "Terça-feira da 18a Semana do Tempo Comum",
      details:
        "São João Maria Vianey (Presbítero e confessor) (Branco – ofício da memória)",
      date: "4 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-4a.html",
    },
    5: {
      img: host + "/images/05_agosto_2020.jpg",
      title: "Quarta-feira da 18a Semana do Tempo Comum",
      details: "(Verde – ofício do dia da semana)",
      date: "5 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-5a.html",
    },
    6: {
      img: host + "/images/06_agosto_2020.jpg",
      title: "Quinta-feira da 18a Semana do Tempo Comum",
      details:
        "Transfiguração do Senhor (Branco, glória, prefácio próprio – ofício da festa)",
      date: "6 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-6a.html",
    },
    7: {
      img: host + "/images/07_agosto_2020.jpg",
      title: "Sexta-feira da 18a Semana do Tempo Comum",
      details: "(verde – ofício do dia)",
      date: "7 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-7a.html",
    },
    8: {
      img: host + "/images/08_agosto_2020.jpg",
      title: "Sábado da 18a Semana do Tempo Comum",
      details:
        "São Domingos, Presbítero e Fundador (Branco – ofício da memória)",
      date: "8 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-8a.html",
    },
    9: {
      img: host + "/images/09_agosto_2020.jpg",
      title: "19º Domingo do tempo comum",
      details: "(Verde, glória, creio - 3ª semana do saltério)",
      date: "9 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-9a.html",
    },
    10: {
      img: host + "/images/10_agosto_2020.jpg",
      title:
        "Segunda-feira da 19ª Semana do Tempo Comum São Lourenço, Diácono e Mártir",
      details: "São Lourenço, Diácono e Mártir(Vermelho - ofício da festa)",
      date: "10 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-10a.html",
    },
    11: {
      img: host + "/images/11_agosto_2020.jpg",
      title: "Terça-feira da 19ª Semana do Tempo Comum",
      details: "Santa Clara - Virgem e Fundadora (Branco - ofício da memória)",
      date: "11 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-11a.html",
    },
    12: {
      img: host + "/images/12_agosto_2020.jpg",
      title: "Quarta-feira da 19ª Semana do Tempo Comum",
      details: "(Verde - ofício do dia)",
      date: "12 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-12a.html",
    },
    13: {
      img: host + "/images/13_agosto_2020.jpg",
      title: "Quinta-feira da 19ª Semana do Tempo Comum",
      details:
        "Santa Dulce dos Pobres (Branco - ofício dos Religiosos ou Santos)",
      date: "13 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-13a.html",
    },
    14: {
      img: host + "/images/14_agosto_2020.jpg",
      title: "Sexta-feira da 19ª Semana do Tempo Comum",
      details:
        "São Maximiliano Maria Kolbe, Presbítero e Mártir (vermelho - ofício da memória)",
      date: "14 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-14a.html",
    },
    15: {
      img: host + "/images/15_agosto_2020.jpg",
      title: "Sábado da 19a Semana do Tempo Comum",
      details: "(Verde – ofício do dia)",
      date: "15 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-15a.html",
    },
    16: {
      img: host + "/images/16_agosto_2020.jpg",
      title: "Domingo da 20ª Semana do Tempo Comum",
      details: "Solenidade da Assunção de Maria (Branco, ofício da solenidade)",
      date: "16 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-16a.html",
    },
    17: {
      img: host + "/images/17_agosto_2020.jpg",
      title: "Segunda-feira da 20ª Semana do Tempo Comum",
      details: "(verde - ofício do dia)",
      date: "17 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-17a.html",
    },
    18: {
      img: host + "/images/18_agosto_2020.jpg",
      title: "Terça-feira da 20ª Semana do Tempo Comum",
      details: "(Verde - ofício do dia)",
      date: "18 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-18a.html",
    },

    19: {
      img: host + "/images/19_agosto_2020.jpg",
      title: "Quarta-feira da 20ª Semana do Tempo Comum",
      details: "(verde - ofício do dia)",
      date: "19 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-19a.html",
    },
    20: {
      img: host + "/images/20_agosto_2020.jpg",
      title: "Quinta-feira da 20ª Semana do Tempo Comum",
      details: "São Bernardo, Abade e Doutor (Branco - ofício da memória)    ",
      date: "20 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-20a.html",
    },
    21: {
      img: host + "/images/21_agosto_2020.jpg",
      title: "Sexta-feira da 20ª Semana do Tempo Comum",
      details: "São Pio 10º, Papa (Branco - ofício da memória)",
      date: "21 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-21a.html",
    },
    22: {
      img: host + "/images/22_agosto_2020.jpg",
      title: "Sábado da 20ª Semana do Tempo Comum",
      details: "Nossa Senhora Rainha (Branco - ofício da memória)",
      date: "22 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-22a.html",
    },
    23: {
      img: host + "/images/23_agosto_2020.jpg",
      title: "Domingo da 21ª Semana do Tempo Comum",
      details: "(Verde)",
      date: "23 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-23a.html",
    },
    24: {
      img: host + "/images/24_agosto_2020.jpg",
      title: "Segunda-feira da 21ª Semana do Tempo Comum",
      details: "São Bartolomeu, Apóstolo (Vermelho - Ofício da festa)",
      date: "24 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-24a.html",
    },
    25: {
      img: host + "/images/25_agosto_2020.jpg",
      title: "Terça-feira da 21ª Semana do Tempo Comum",
      details: "(Verde - Ofício do dia)",
      date: "25 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-25a.html",
    },
    26: {
      img: host + "/images/26_agosto_2020.jpg",
      title: "Quarta-feira da 21ª Semana do Tempo Comum",
      details: "(Verde - Ofício do dia)",
      date: "26 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-26a.html",
    },
    27: {
      img: host + "/images/27_agosto_2020.jpg",
      title: "Quinta-feira da 21ª Semana do Tempo Comum",
      details: "Santa Mônica, Esposa, Mãe e Viúva (Branco - Ofício da memória)",
      date: "27 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-27a.html",
    },
    28: {
      img: host + "/images/28_agosto_2020.jpg",
      title: "Sexta-feira da 21ª Semana do Tempo Comum",
      details: "Santo Agostinho, Bispo e Doutor (Branco - Ofício da memória)",
      date: "28 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-28a.html",
    },
    29: {
      img: host + "/images/29_agosto_2020.jpg",
      title: "Sábado da 21ª Semana do Tempo Comum",
      details: "Martírio de São João Batista (Vermelho - Ofício da memória)",
      date: "29 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-29a.html",
    },
    30: {
      img: host + "/images/30_agosto_2020.jpg",
      title: "Domingo da 22º Domingo do Tempo Comum",
      details: "(Verde-Ofício dominical comum)",
      date: "30 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-30a.html",
    },
    31: {
      img: host + "/images/31_agosto_2020.jpg",
      title: "Segunda-feira da 22ª Semana do Tempo Comum",
      details: "(Verde-Ofício do dia)",
      date: "31 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-31a.html",
    },
  },

  September: {
    1: {
      img: host + "/images/01_setembro_2020_Leit_Oran.jpg",
      title: "Terça-feira da 22ª Semana do Tempo Comum",
      details:    "(Verde -Ofício do dia)",
      date: "1 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-1a.html",
    },
    2: {
      img: host + "/images/02_setembro_2020_Leit_Oran.jpg",
      title: "Quarta-feira da 22ª Semana do Tempo Comum",
      details: "(Verde -Ofício do dia)",
      date: "2 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-2a.html",
    },
    3: {
      img: host + "/images/03_setembro_2020_Leit_Oran.jpg",
      title: "São Gregório Magno - Papa e Doutor da Igreja      ",
      details: "Quinta-feira da 22ª Semana do Tempo Comum (Branco - Ofício da memória)",
      date: "3 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-3a.html",
    },
    4: {
      img: host + "/images/04_setembro_2020_Leit_Oran.jpg",
      title: "Sexta-feira da 22ª Semana do Tempo Comum",
      details:
        "(Verde -Ofício do dia)",
      date: "4 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-4a.html",
    },
    5: {
      img: host + "/images/05_setembro_2020_Leit_Oran.jpg",
      title: "Sábado da 22ª Semana do Tempo Comum",
      details: "(Verde -Ofício do dia)",
      date: "5 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-5a.html",
    },
    6: {
      img: host + "/images/06_setembro_2020_Leit_Oran.jpg",
      title: "Domingo - 23ª Semana do Tempo Comum",
      details:
        "(Verde -Ofício do dia)",
      date: "6 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-6a.html",
    },
    7: {
      img: host + "/images/07_setembro_2020_Leit_Oran.jpg",
      title: "Segunda-feira - 23ª Semana do Tempo Comum",
      details: "(Verde - Ofício do dia)",
      date: "7 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-7a.html",
    },
    8: {
      img: host + "/images/08_setembro_2020_Leit_Oran.jpg",
      title: "Terça-feira - Natividade de Nossa Senhora",
      details:
        "(Branco - Ofício da festa)",
      date: "8 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-8a.html",
    },
 
    9: {
      img: host + "/images/09_setembro_2020_Leit_Oran.jpg",
      title: "Quarta-feira - 22ª Semana do Tempo Comum",
      details: "(Verde -Ofício do dia)",
      date: "9 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-9a.html",
    },
    10: {
      img: host + "/images/10_setembro_2020_Leit_Oran.jpg",
      title:
        "Quinta-feira da 23ª Semana do Tempo Comum",
      details: "(Verde - Ofício do dia)",
      date: "10 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-10a.html",
    },
    11: {
      img: host + "/images/11_setembro_2020_Leit_Oran.jpg",
      title: "Sexta-feira da 23ª Semana do Tempo Comum",
      details: "(Verde - Ofício do dia)",
      date: "11 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-11a.html",
    },
    12: {
      img: host + "/images/12_setembro_2020_Leit_Oran.jpg",
      title: "Sábado da 23ª Semana do Tempo Comum",
      details: "(Verde -Ofício do dia)",
      date: "12 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-12a.html",
    },
    13: {
      img: host + "/images/13_setembro_2020_Leit_Oran.jpg",
      title: "Domingo da 24ª Semana do Tempo Comum",
      details:
        "(Verde - Ofício do dia)",
      date: "13 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-13a.html",
    },
    14: {
      img: host + "/images/14_setembro_2020_Leit_Oran.jpg",
      title: "Segunda-feira - Exaltação da Santa Cruz",
      details:
        "(Verde -Ofício do dia)",
      date: "14 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-14a.html",
    },
    15: {
      img: host + "/images/15_setembro_2020_Leit_Oran.jpg",
      title: "Terça-feira da 24ª Semana do Tempo Comum  Nossa Senhora das Dores",
      details: "(Branco - Ofício da memória)",
      date: "15 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-15a.html",
    },
    16: {
      img: host + "/images/16_setembro_2020_Leit_Oran.jpg",
      title: "Quarta-feira da 24ª Semana do Tempo Comum  Santos Cornélio e Cipriano - Papa e Bispo Mártires",
      details: "(Verde -Ofício do dia)",
      date: "16 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-16a.html",
    },
    17: {
      img: host + "/images/17_setembro_2020_Leit_Oran.jpg",
      title: "Quarta-feira da 24ª Semana do Tempo Comum Santos Cornélio e Cipriano - Papa e Bispo Mártires",
      details: "(Verde - ofício do dia)",
      date: "17 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-17a.html",
    },
    18: {
      img: host + "/images/18_setembro_2020_Leit_Oran.jpg",
      title: "Sexta-feira - 24ª semana do tempo comum",
      details: "(Verde - ofício do dia)",
      date: "18 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-18a.html",
    },

    19: {
      img: host + "/images/19_setembro_2020_Leit_Oran.jpg",
      title: "Sábado - 24ª semana do tempo comum São Januário",
      details: "(Verde - ofício do dia)",
      date: "19 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-19a.html",
    },
    20: {
      img: host + "/images/20_setembro_2020_Leit_Oran.jpg",
      title: "Domingo - 25a semana do tempo comum",
      details: "(Verde - Ofício do dia)",
      date: "20 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-20a.html",
    },
    21: {
      img: host + "/images/21_setembro_2020_Leit_Oran.jpg",
      title: "Segunda-feira - São Mateus, Apóstolo e Evangelista",
      details: "(Vermelho - Ofício da festa)",
      date: "21 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-21a.html",
    },
    22: {
      img: host + "/images/22_setembro_2020_Leit_Oran.jpg",
      title: "Terça-feira - 25ª semana do tempo comum",
      details: "(Verde - Ofício do dia)      ",
      date: "22 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-22a.html",
    },
    23: {
      img: host + "/images/23_setembro_2020_Leit_Oran.jpg",
      title: "Quarta-feira - São Pio de Pietrelcina, Presbítero",
      details: "(Verde -Ofício da memória)",
      date: "23 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-23a.html",
    },
    24: {
      img: host + "/images/24_setembro_2020_Leit_Oran.jpg",
      title: "Quinta-feira - 25ª semana do tempo comum",
      details: "(Verde -Ofício da memória)",
      date: "24 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-24a.html",
    },
    25: {
      img: host + "/images/25_setembro_2020_Leit_Oran.jpg",
      title: "Sexta-feira - 25ª semana do tempo comum",
      details: "(Verde - Ofício do dia)",
      date: "25 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-25a.html",
    },
    26: {
      img: host + "/images/26_setembro_2020_Leit_Oran.jpg",
      title: "Sábado - 25a semana do tempo comum",
      details: "(Verde - Ofício do dia ou Memória facultativa: São Cosme e São Damião - Mártires, cor vermelha )",
      date: "26 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-26a.html",
    },
    27: {
      img: host + "/images/27_setembro_2020_Leit_Oran.jpg",
      title: "Domingo - 26ª semana do tempo comum Dia Nacional da Bíblia",
      details: "(Verde -Ofício da memória)",
      date: "27 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-27a.html",
    },
    28: {
      img: host + "/images/28_setembro_2020_Leit_Oran.jpg",
      title: "Segunda-feira - 26ª semana do tempo comum",
      details: "(Verde -Ofício da memória)",
      date: "28 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-28a.html",
    },
    29: {
      img: host + "/images/29_setembro_2020_Leit_Oran.jpg",
      title: "Terça-feira - Santos Arcanjos Miguel, Gabriel e Rafael",
      details: "(Verde -Ofício da memória)",
      date: "29 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-29a.html",
    },
    30: {
      img: host + "/images/30_setembro_2020_Leit_Oran.jpg",
      title: "Quarta-feira - São Jerônimo, Presbítero e Doutor",
      details: "(Verde -Ofício da memória)",
      date: "30 de setembro de 2020",
      route: host + "/Leitura-Orante-September/leitura-orante-30a.html",
    },
  },

  October: {
    1: {
      img: host + "/images/01_Outubro_2020_Leit_Oran.jpg",
      title: "17ª Semana do Tempo Comum",
      details:
        "Santo Afonso Maria de Ligório (bispo, doutor e fundador) (Branca - ofício da memória)",
      date: "1 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-1a.html",
    },
    2: {
      img: host + "/images/02_Outubro_2020_Leit_Oran.jpg",
      title: "18º Domingo Do Tempo Comum",
      details: "(Verde - ofício dominical comum)",
      date: "2 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-2a.html",
    },
    3: {
      img: host + "/images/03_Outubro_2020_Leit_Oran.jpg",
      title: "Segunda-feira da 18ª Semana Comum",
      details: "(Verde – ofício do dia)",
      date: "3 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-3a.html",
    },
    4: {
      img: host + "/images/04_Outubro_2020_Leit_Oran.jpg",
      title: "Terça-feira da 18a Semana do Tempo Comum",
      details:
        "São João Maria Vianey (Presbítero e confessor) (Branco – ofício da memória)",
      date: "4 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-4a.html",
    },
    5: {
      img: host + "/images/05_Outubro_2020_Leit_Oran.jpg",
      title: "Quarta-feira da 18a Semana do Tempo Comum",
      details: "(Verde – ofício do dia da semana)",
      date: "5 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-5a.html",
    },
    6: {
      img: host + "/images/06Outubro_2020_Leit_Oran.jpg",
      title: "Quinta-feira da 18a Semana do Tempo Comum",
      details:
        "Transfiguração do Senhor (Branco, glória, prefácio próprio – ofício da festa)",
      date: "6 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-6a.html",
    },
    7: {
      img: host + "/images/07Outubro_2020_Leit_Oran.jpg",
      title: "Sexta-feira da 18a Semana do Tempo Comum",
      details: "(verde – ofício do dia)",
      date: "7 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-7a.html",
    },
    8: {
      img: host + "/images/08_Outubro_Leit_Oran.jpg",
      title: "Sábado da 18a Semana do Tempo Comum",
      details:
        "São Domingos, Presbítero e Fundador (Branco – ofício da memória)",
      date: "8 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-8a.html",
    },
    9: {
      img: host + "/images/09_Outubro_2020_Leit_Oran.jpg",
      title: "19º Domingo do tempo comum",
      details: "(Verde, glória, creio - 3ª semana do saltério)",
      date: "9 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-9a.html",
    },
    10: {
      img: host + "/images/10_Outubro_2020_Leit_Oran.jpg",
      title:
        "Segunda-feira da 19ª Semana do Tempo Comum São Lourenço, Diácono e Mártir",
      details: "São Lourenço, Diácono e Mártir(Vermelho - ofício da festa)",
      date: "10 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-10a.html",
    },
    11: {
      img: host + "/images/11_Outubro_2020_Leit_Oran.jpg",
      title: "Terça-feira da 19ª Semana do Tempo Comum",
      details: "Santa Clara - Virgem e Fundadora (Branco - ofício da memória)",
      date: "11 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-11a.html",
    },
    12: {
      img: host + "/images/12_Outubro_2020_Leit_Oran.jpg",
      title: "Quarta-feira da 19ª Semana do Tempo Comum",
      details: "(Verde - ofício do dia)",
      date: "12 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-12a.html",
    },
    13: {
      img: host + "/images/13_Outubro_2020_Leit_Oran.jpg",
      title: "Quinta-feira da 19ª Semana do Tempo Comum",
      details:
        "Santa Dulce dos Pobres (Branco - ofício dos Religiosos ou Santos)",
      date: "13 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-13a.html",
    },
    14: {
      img: host + "/images/14_Outubro_2020_leit_Oran.jpg",
      title: "Sexta-feira da 19ª Semana do Tempo Comum",
      details:
        "São Maximiliano Maria Kolbe, Presbítero e Mártir (vermelho - ofício da memória)",
      date: "14 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-14a.html",
    },
    15: {
      img: host + "/images/15_Outubro_Leit_Oran.jpg",
      title: "Sábado da 19a Semana do Tempo Comum",
      details: "(Verde – ofício do dia)",
      date: "15 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-15a.html",
    },
    16: {
      img: host + "/images/16_Outubro_2020_leit_Oran.jpg",
      title: "Domingo da 20ª Semana do Tempo Comum",
      details: "Solenidade da Assunção de Maria (Branco, ofício da solenidade)",
      date: "16 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-16a.html",
    },
    17: {
      img: host + "/images/17_Outubro_2020_Leit_Oran.jpg",
      title: "Segunda-feira da 20ª Semana do Tempo Comum",
      details: "(verde - ofício do dia)",
      date: "17 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-17a.html",
    },
    18: {
      img: host + "/images/18_Outubro_2020_Leit_Oran.jpg",
      title: "Terça-feira da 20ª Semana do Tempo Comum",
      details: "(Verde - ofício do dia)",
      date: "18 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-18a.html",
    },

    19: {
      img: host + "/images/19_Outubro_2020_Leit_Oran.jpg",
      title: "Quarta-feira da 20ª Semana do Tempo Comum",
      details: "(verde - ofício do dia)",
      date: "19 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-19a.html",
    },
    20: {
      img: host + "/images/20_Outubro_2020_Leit_Oran.jpg",
      title: "Quinta-feira da 20ª Semana do Tempo Comum",
      details: "São Bernardo, Abade e Doutor (Branco - ofício da memória)    ",
      date: "20 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-20a.html",
    },
    21: {
      img: host + "/images/13_Outubro_2020_Leit_Oran.jpg",
      title: "Sexta-feira da 20ª Semana do Tempo Comum",
      details: "São Pio 10º, Papa (Branco - ofício da memória)",
      date: "21 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-21a.html",
    },
    22: {
      img: host + "/images/22_Outubro_2020_Leit_Oran.jpg",
      title: "Sábado da 20ª Semana do Tempo Comum",
      details: "Nossa Senhora Rainha (Branco - ofício da memória)",
      date: "22 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-22a.html",
    },
    23: {
      img: host + "/images/23_Outubro_2020_Leit_Oran.jpg",
      title: "Domingo da 21ª Semana do Tempo Comum",
      details: "(Verde)",
      date: "23 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-23a.html",
    },
    24: {
      img: host + "/images/24_Outubro_2020_Leit_Oran.jpg",
      title: "Segunda-feira da 21ª Semana do Tempo Comum",
      details: "São Bartolomeu, Apóstolo (Vermelho - Ofício da festa)",
      date: "24 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-24a.html",
    },
    25: {
      img: host + "/images/25_Outubro_2020_leit_Oran.jpg",
      title: "Terça-feira da 21ª Semana do Tempo Comum",
      details: "(Verde - Ofício do dia)",
      date: "25 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-25a.html",
    },
    // 26: {
    //   img: host + "/images/26_agosto_2020.jpg",
    //   title: "Quarta-feira da 21ª Semana do Tempo Comum",
    //   details: "(Verde - Ofício do dia)",
    //   date: "26 de agosto de 2020",
    //   route: host + "/Leitura-Orante/leitura-orante-26a.html",
    // },
    27: {
      img: host + "/images/27_Outubro_2020_Leit_Oran.jpg",
      title: "Quinta-feira da 21ª Semana do Tempo Comum",
      details: "Santa Mônica, Esposa, Mãe e Viúva (Branco - Ofício da memória)",
      date: "27 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-27a.html",
    },
    28: {
      img: host + "/images/28_Outubro_2020_Leit_Oran.jpg",
      title: "Sexta-feira da 21ª Semana do Tempo Comum",
      details: "Santo Agostinho, Bispo e Doutor (Branco - Ofício da memória)",
      date: "28 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-28a.html",
    },
    29: {
      img: host + "/images/29_Outubro_2020_Leit_Oran.jpg",
      title: "Sábado da 21ª Semana do Tempo Comum",
      details: "Martírio de São João Batista (Vermelho - Ofício da memória)",
      date: "29 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-29a.html",
    },
    30: {
      img: host + "/images/30_Outubro_2020_Leit_Oran.jpg",
      title: "Domingo da 22º Domingo do Tempo Comum",
      details: "(Verde-Ofício dominical comum)",
      date: "30 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-30a.html",
    },
    31: {
      img: host + "/images/31_Outubro_2020_Leit_Oran.jpg",
      title: "Segunda-feira da 22ª Semana do Tempo Comum",
      details: "(Verde-Ofício do dia)",
      date: "31 de agosto de 2020",
      route: host + "/Leitura-Orante/leitura-orante-31a.html",
    },
  },

};
